name: Kustomize yaml validation
description: "Github Action that validates yaml and kustomization outputs with yq and kubeconform"
branding:
  icon: align-justify
  color: blue
inputs:
  kubeconform-verbose:
    description: "Boolean variable to enable verbose kubeconform outputs"
    required: true
    default: "false"
  flux-directory:
    description: "Root directory of the flux installation, default is ./clusters"
    required: true
    default: "./clusters"
  target-directories:
    description: "List of target directories, by default all directories will be checked"
    required: true
    default: "__ALL__"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: validate.sh ${{ inputs.kubeconform-verbose }} ${{ inputs.flux-directory }} "${{ inputs.target-directories }}"
      shell: bash
